UPDATE WSHOP.PRODUTO SET IdCalculoICMS = '' WHERE IdCalculoICMS LIKE '999AAA%';
DELETE FROM WSHOP.ICMS_UF WHERE IdCalculoICMS LIKE '999AAA%';
DELETE FROM WSHOP.ICMS WHERE IdCalculoICMS LIKE '999AAA%';