package br.com.alertafiscal.opusprimum.gui;

import br.com.alertafiscal.opusprimum.Componente;
import br.com.alertafiscal.opusprimum.FluxoPrincipal;
import br.com.alertafiscal.opusprimum.gui.config.ConfiguracaoGUI;
import br.com.alertafiscal.opusprimum.log.impl.LoggerGUI;
import br.com.alertafiscal.opusprimum.log.LoggerFachada;
import br.com.alertafiscal.opusprimum.utils.DiretorioUtils;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author bastosbf
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public PrincipalGUI() {
        initComponents();
    }

    public void executa(String tipoExecucao) {
        LoggerGUI logger = new LoggerGUI(textAreaNotificacoes, labelContadorAtualizacoes);
        LoggerFachada loggerFachada = new LoggerFachada(logger);
        Componente.setLogger(loggerFachada);
        try {
            FluxoPrincipal.rodar(tipoExecucao, loggerFachada);
        } catch (Exception ex) {
            loggerFachada.exception(ex);
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao tentar executar o Opus, entre em contato com o suporte!");
        } finally {
            botaoFechar.setEnabled(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelOpusPrimum = new javax.swing.JLabel();
        painelNotificacoes = new javax.swing.JPanel();
        scrollPaneNotificacoes = new javax.swing.JScrollPane();
        textAreaNotificacoes = new javax.swing.JTextArea();
        labelContadorAtualizacoes = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        botaoFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Opus Primum");
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        labelOpusPrimum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOpusPrimum.setText("Opus Primum - 2.0.3");

        textAreaNotificacoes.setColumns(20);
        textAreaNotificacoes.setRows(5);
        scrollPaneNotificacoes.setViewportView(textAreaNotificacoes);

        javax.swing.GroupLayout painelNotificacoesLayout = new javax.swing.GroupLayout(painelNotificacoes);
        painelNotificacoes.setLayout(painelNotificacoesLayout);
        painelNotificacoesLayout.setHorizontalGroup(
            painelNotificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNotificacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelNotificacoesLayout.setVerticalGroup(
            painelNotificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelNotificacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                .addContainerGap())
        );

        labelContadorAtualizacoes.setText("Contador de atualizações....");

        botaoFechar.setText("Fechar");
        botaoFechar.setEnabled(false);
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelBotoesLayout = new javax.swing.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoFechar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(painelBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(labelContadorAtualizacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelOpusPrimum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelOpusPrimum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelNotificacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelContadorAtualizacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        dispose();
    }//GEN-LAST:event_botaoFecharActionPerformed

    public static void rodar(String tipoExecucao) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        PrincipalGUI gui = new PrincipalGUI();
        gui.setVisible(true);
        gui.executa(tipoExecucao);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFechar;
    private javax.swing.JLabel labelContadorAtualizacoes;
    private javax.swing.JLabel labelOpusPrimum;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelNotificacoes;
    private javax.swing.JScrollPane scrollPaneNotificacoes;
    private javax.swing.JTextArea textAreaNotificacoes;
    // End of variables declaration//GEN-END:variables
}
