/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.alertafiscal.opusprimum.gui.config;

import br.com.alertafiscal.opusprimum.gui.PrincipalGUI;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Bruno
 */
public class ConfiguracaoGUI extends javax.swing.JFrame {

    private final static String CHAVE_AMBIENTE = "opus.ambiente";
    private final static String CHAVE_TIPO_ENTRADA = "opus.tipo.entrada";
    private final static String CHAVE_MODELO_ENTRADA = "opus.tipo.entrada.versao";
    private final static String CHAVE_MODALIDADE_JURIDICA = "opus.modalidade.juridica";

    private final static String CHAVE_EMAIL_SERVIDOR = "email.smtp.servidor";
    private final static String CHAVE_EMAIL_PORTA = "email.smtp.porta";
    private final static String CHAVE_EMAIL_USUARIO = "email.smtp.usuario";
    private final static String CHAVE_EMAIL_SENHA = "email.smtp.senha";
    private final static String CHAVE_EMAIL_DESTINATARIO = "email.relatorio";

    private final static String CHAVE_WEBSERVICE_URL = "webservice.url";
    private final static String CHAVE_WEBSERVICE_ID = "webservice.id";
    private final static String CHAVE_WEBSERVICE_TOKEN = "webservice.token";

    private final static String CHAVE_XML_CAMINHO = "xml.caminho";

    private final static String CHAVE_HIBERNATE_DIALECT = "hibernate.dialect";
    private final static String CHAVE_HIBERNATE_DRIVER = "hibernate.connection.driver_class";
    private final static String CHAVE_HIBERNATE_URL = "hibernate.connection.url";
    private final static String CHAVE_HIBERNATE_USERNAME = "hibernate.connection.username";
    private final static String CHAVE_HIBERNATE_PASSWORD = "hibernate.connection.password";

    private final static String CHAVE_ALTERDATA_CFOPS = "alterdata.cfops";
    private final static String CHAVE_ALTERDATA_ESTADOS_ENTRADA = "alterdata.estados.entrada";
    private final static String CHAVE_ALTERDATA_ESTADOS_SAIDA = "alterdata.estados.saida";

    private final static String CHAVE_RETAGUARDA = "retaguarda.impl";

    private final static String AMBIENTE_DESENVOLVIMENTO = "Desenvolvimento";
    private final static String AMBIENTE_PRODUCAO = "Produção";

    private static final String TIPO_ENTRADA_XML = "XML";
    private static final String TIPO_ENTRADA_WEBSERVICE = "Web Service";

    private static final String MODELO_ENTRADA_SOAP_FINAL_RJ = "SOAP Final RJ";
    private static final String MODELO_ENTRADA_MODELO_ANTIGO = "Modelo Antigo";

    private static final String MODALIDADE_JURIDICA_SIMPLES = "Simples";
    private static final String MODALIDADE_JURIDICA_LUCRO_REAL = "Lucro Real";
    private static final String MODALIDADE_JURIDICA_LUCRO_PRESUMIDO = "Lucro Presumido";

    private static final String RETAGUARDA_ALTERDATA_POSTGRESQL = "Alterdata PostgreSQL";
    private static final String RETAGUARDA_ALTERDATA_POSTGRESQL_DIALECT = "org.hibernate.dialect.PostgreSQLDialect";
    private static final String RETAGUARDA_ALTERDATA_POSTGRESQL_DRIVER = "org.postgresql.Driver";
    private static final String RETAGUARDA_ALTERDATA_POSTGRESQL_RETAGUARDA = "br.com.alertafiscal.opusprimum.retaguarda.alterdata.postgresql.RetaguardaAlterdataPostgreSQL";

    private static final String RETAGUARDA_ALTERDATA_SQLSERVER = "Alterdata SQLServer";
    private static final String RETAGUARDA_ALTERDATA_SQLSERVER_DIALECT = "org.hibernate.dialect.SQLServerDialect";
    private static final String RETAGUARDA_ALTERDATA_SQLSERVER_DRIVER = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private static final String RETAGUARDA_ALTERDATA_SQLSERVER_RETAGUARDA = "br.com.alertafiscal.opusprimum.retaguarda.alterdata.sqlserver.RetaguardaAlterdataSQLServer";

    /*
     * Creates new form ConfiguracaoGUI
     */
    public ConfiguracaoGUI() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelConfiguracoes = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JTabbedPane();
        painelRevisao = new javax.swing.JPanel();
        labelAmbiente = new javax.swing.JLabel();
        comboBoxAmbiente = new javax.swing.JComboBox();
        labelTipoEntrada = new javax.swing.JLabel();
        comboBoxTipoEntrada = new javax.swing.JComboBox();
        labelModeloEntrada = new javax.swing.JLabel();
        comboBoxModeloEntrada = new javax.swing.JComboBox();
        labelModalidadeJuridica = new javax.swing.JLabel();
        comboBoxModalidadeJuridica = new javax.swing.JComboBox();
        painelRevisaoXML = new javax.swing.JPanel();
        labelArquivo = new javax.swing.JLabel();
        textoArquivo = new javax.swing.JTextField();
        botaoArquivo = new javax.swing.JButton();
        painelRevisaoWebService = new javax.swing.JPanel();
        labelURL = new javax.swing.JLabel();
        textoURL = new javax.swing.JTextField();
        labelID = new javax.swing.JLabel();
        textoID = new javax.swing.JTextField();
        labelToken = new javax.swing.JLabel();
        textoToken = new javax.swing.JTextField();
        painelEmail = new javax.swing.JPanel();
        labelServidor = new javax.swing.JLabel();
        textoServidor = new javax.swing.JTextField();
        labelPorta = new javax.swing.JLabel();
        textoPorta = new javax.swing.JTextField();
        labelUsuario = new javax.swing.JLabel();
        textoUsuario = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        textoSenha = new javax.swing.JTextField();
        labelDestinatario = new javax.swing.JLabel();
        textoDestinatario = new javax.swing.JTextField();
        painelBancoDeDados = new javax.swing.JPanel();
        labelSistema = new javax.swing.JLabel();
        comboBoxSistema = new javax.swing.JComboBox();
        labelStringDeConexao = new javax.swing.JLabel();
        textoStringDeConexao = new javax.swing.JTextField();
        labelUsuarioBD = new javax.swing.JLabel();
        textoUsuarioBD = new javax.swing.JTextField();
        labelSenhaBD = new javax.swing.JLabel();
        textoSenhaBD = new javax.swing.JTextField();
        painelAlterdata = new javax.swing.JPanel();
        labelCFOPs = new javax.swing.JLabel();
        textoCFOPs = new javax.swing.JTextField();
        labelEstadosEntrada = new javax.swing.JLabel();
        textoEstadosEntrada = new javax.swing.JTextField();
        labelEstadosSaida = new javax.swing.JLabel();
        textoEstadosSaida = new javax.swing.JTextField();
        botaoSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configurações do Opus Primum");

        labelConfiguracoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfiguracoes.setText("Configurações do Opus Primum");

        labelAmbiente.setText("Ambiente:");

        comboBoxAmbiente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Produção", "Desenvolvimento" }));

        labelTipoEntrada.setText("Tipo da Entrada:");

        comboBoxTipoEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "XML", "Web Service" }));
        comboBoxTipoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoEntradaActionPerformed(evt);
            }
        });

        labelModeloEntrada.setText("Modelo de Entrada:");

        comboBoxModeloEntrada.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SOAP Final RJ", "Modelo Antigo" }));
        comboBoxModeloEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxModeloEntradaActionPerformed(evt);
            }
        });

        labelModalidadeJuridica.setText("Modalidade Jurídica:");

        comboBoxModalidadeJuridica.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Lucro Real", "Lucro Presumido" }));

        painelRevisaoXML.setBorder(javax.swing.BorderFactory.createTitledBorder("XML"));

        labelArquivo.setText("Arquivo:");

        botaoArquivo.setText("Selecionar");
        botaoArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoArquivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelRevisaoXMLLayout = new javax.swing.GroupLayout(painelRevisaoXML);
        painelRevisaoXML.setLayout(painelRevisaoXMLLayout);
        painelRevisaoXMLLayout.setHorizontalGroup(
            painelRevisaoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRevisaoXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoArquivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoArquivo)
                .addContainerGap())
        );
        painelRevisaoXMLLayout.setVerticalGroup(
            painelRevisaoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRevisaoXMLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRevisaoXMLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArquivo)
                    .addComponent(textoArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoArquivo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelRevisaoWebService.setBorder(javax.swing.BorderFactory.createTitledBorder("Web Service"));
        painelRevisaoWebService.setEnabled(false);

        labelURL.setText("URL:");

        textoURL.setEnabled(false);

        labelID.setText("ID:");

        textoID.setEnabled(false);

        labelToken.setText("Token:");

        textoToken.setEnabled(false);

        javax.swing.GroupLayout painelRevisaoWebServiceLayout = new javax.swing.GroupLayout(painelRevisaoWebService);
        painelRevisaoWebService.setLayout(painelRevisaoWebServiceLayout);
        painelRevisaoWebServiceLayout.setHorizontalGroup(
            painelRevisaoWebServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRevisaoWebServiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRevisaoWebServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelID)
                    .addComponent(labelToken)
                    .addComponent(labelURL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRevisaoWebServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoURL, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoToken, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        painelRevisaoWebServiceLayout.setVerticalGroup(
            painelRevisaoWebServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelRevisaoWebServiceLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(painelRevisaoWebServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelURL)
                    .addComponent(textoURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRevisaoWebServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelID)
                    .addComponent(textoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRevisaoWebServiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelToken)
                    .addComponent(textoToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout painelRevisaoLayout = new javax.swing.GroupLayout(painelRevisao);
        painelRevisao.setLayout(painelRevisaoLayout);
        painelRevisaoLayout.setHorizontalGroup(
            painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRevisaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelRevisaoLayout.createSequentialGroup()
                        .addGroup(painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAmbiente)
                            .addComponent(labelTipoEntrada)
                            .addComponent(labelModeloEntrada)
                            .addComponent(labelModalidadeJuridica))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboBoxAmbiente, javax.swing.GroupLayout.Alignment.TRAILING, 0, 742, Short.MAX_VALUE)
                            .addComponent(comboBoxTipoEntrada, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxModeloEntrada, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxModalidadeJuridica, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(painelRevisaoXML, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelRevisaoWebService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelRevisaoLayout.setVerticalGroup(
            painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelRevisaoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAmbiente)
                    .addComponent(comboBoxAmbiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTipoEntrada)
                    .addComponent(comboBoxTipoEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelModeloEntrada)
                    .addComponent(comboBoxModeloEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelRevisaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelModalidadeJuridica)
                    .addComponent(comboBoxModalidadeJuridica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(painelRevisaoXML, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelRevisaoWebService, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelPrincipal.addTab("Revisão", painelRevisao);

        labelServidor.setText("Servidor:");

        textoServidor.setEnabled(false);

        labelPorta.setText("Porta:");

        textoPorta.setEnabled(false);

        labelUsuario.setText("Usuário:");

        textoUsuario.setEnabled(false);

        labelSenha.setText("Senha:");

        textoSenha.setEnabled(false);

        labelDestinatario.setText("Destinatário:");

        textoDestinatario.setEnabled(false);

        javax.swing.GroupLayout painelEmailLayout = new javax.swing.GroupLayout(painelEmail);
        painelEmail.setLayout(painelEmailLayout);
        painelEmailLayout.setHorizontalGroup(
            painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelServidor)
                    .addComponent(labelPorta)
                    .addComponent(labelUsuario)
                    .addComponent(labelSenha)
                    .addComponent(labelDestinatario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoDestinatario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(textoSenha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(textoPorta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
                    .addComponent(textoServidor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        painelEmailLayout.setVerticalGroup(
            painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelEmailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServidor)
                    .addComponent(textoServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPorta)
                    .addComponent(textoPorta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(textoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(textoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelEmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDestinatario)
                    .addComponent(textoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        painelPrincipal.addTab("E-mail (SMTP)", painelEmail);

        labelSistema.setText("Sistema:");

        comboBoxSistema.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alterdata PostgreSQL", "Alterdata SQLServer" }));

        labelStringDeConexao.setText("String de Conexão:");

        labelUsuarioBD.setText("Usuário:");

        labelSenhaBD.setText("Senha:");

        painelAlterdata.setBorder(javax.swing.BorderFactory.createTitledBorder("Alterdata"));

        labelCFOPs.setText("CFOPs (separados por vírgula):");

        textoCFOPs.setText("1102,1202,1209,1401,1403,1405,1551,1556,1910,1949,2102,2401,2403,2405,2910,2949,5101,5102,5202,5401,5402,5403,5405,5410,5411,5915,5916,5927,5949,6102,6202,6401,6404,6410,6411,6910,6915");
        textoCFOPs.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textoCFOPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoCFOPsActionPerformed(evt);
            }
        });

        labelEstadosEntrada.setText("Estados de Entrada (sepados por vírgula):");

        textoEstadosEntrada.setText("RJ,SP,MG,RS,ES,PA,PR,SC");
        textoEstadosEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEstadosEntradaActionPerformed(evt);
            }
        });

        labelEstadosSaida.setText("Estados de Saída (sepados por vírgula):");

        textoEstadosSaida.setText("RJ");
        textoEstadosSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoEstadosSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelAlterdataLayout = new javax.swing.GroupLayout(painelAlterdata);
        painelAlterdata.setLayout(painelAlterdataLayout);
        painelAlterdataLayout.setHorizontalGroup(
            painelAlterdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterdataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelAlterdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCFOPs)
                    .addComponent(labelEstadosEntrada)
                    .addComponent(labelEstadosSaida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlterdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoEstadosEntrada, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoCFOPs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(textoEstadosSaida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelAlterdataLayout.setVerticalGroup(
            painelAlterdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAlterdataLayout.createSequentialGroup()
                .addGroup(painelAlterdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCFOPs)
                    .addComponent(textoCFOPs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlterdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadosEntrada)
                    .addComponent(textoEstadosEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelAlterdataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstadosSaida)
                    .addComponent(textoEstadosSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout painelBancoDeDadosLayout = new javax.swing.GroupLayout(painelBancoDeDados);
        painelBancoDeDados.setLayout(painelBancoDeDadosLayout);
        painelBancoDeDadosLayout.setHorizontalGroup(
            painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBancoDeDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelAlterdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelBancoDeDadosLayout.createSequentialGroup()
                        .addGroup(painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSistema)
                            .addComponent(labelStringDeConexao)
                            .addComponent(labelUsuarioBD)
                            .addComponent(labelSenhaBD))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoUsuarioBD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoStringDeConexao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textoSenhaBD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboBoxSistema, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        painelBancoDeDadosLayout.setVerticalGroup(
            painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelBancoDeDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSistema)
                    .addComponent(comboBoxSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStringDeConexao)
                    .addComponent(textoStringDeConexao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuarioBD)
                    .addComponent(textoUsuarioBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelBancoDeDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenhaBD)
                    .addComponent(textoSenhaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelAlterdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        painelPrincipal.addTab("Banco de Dados", painelBancoDeDados);

        botaoSalvar.setText("Salvar e Executar Opus Primum");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConfiguracoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(painelPrincipal)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConfiguracoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoCFOPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoCFOPsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoCFOPsActionPerformed

    private void textoEstadosEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEstadosEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEstadosEntradaActionPerformed

    private void textoEstadosSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoEstadosSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoEstadosSaidaActionPerformed

    private void comboBoxTipoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoEntradaActionPerformed
        String valor = obtemValorSelecionado(comboBoxTipoEntrada);
        if (TIPO_ENTRADA_XML.equals(valor)) {
            painelRevisaoXML.setEnabled(true);
            textoArquivo.setEnabled(true);
            painelRevisaoWebService.setEnabled(false);
            textoID.setEnabled(false);
            textoToken.setEnabled(false);
            textoURL.setEnabled(false);
        } else if (TIPO_ENTRADA_WEBSERVICE.equals(valor)) {
            painelRevisaoXML.setEnabled(false);
            textoArquivo.setEnabled(false);
            painelRevisaoWebService.setEnabled(true);
            textoID.setEnabled(true);
            textoToken.setEnabled(true);
            textoURL.setEnabled(true);
        }
    }//GEN-LAST:event_comboBoxTipoEntradaActionPerformed

    private void comboBoxModeloEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxModeloEntradaActionPerformed

    }//GEN-LAST:event_comboBoxModeloEntradaActionPerformed

    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        File arquivoConfiguracoesLocal = new File("config.properties");
        Properties propriedades = new Properties();
        String ambiente = obtemValorSelecionado(comboBoxAmbiente);
        switch (ambiente) {
            case AMBIENTE_PRODUCAO:
                propriedades.put(CHAVE_AMBIENTE, "producao");
                break;
            case AMBIENTE_DESENVOLVIMENTO:
                propriedades.put(CHAVE_AMBIENTE, "desenvolvimento");
                break;
        }
        String tipoEntrada = obtemValorSelecionado(comboBoxTipoEntrada);
        switch (tipoEntrada) {
            case TIPO_ENTRADA_XML:
                propriedades.put(CHAVE_TIPO_ENTRADA, "xml");
                String caminho = textoArquivo.getText();
                propriedades.put(CHAVE_XML_CAMINHO, caminho);
                break;
            case TIPO_ENTRADA_WEBSERVICE:
                propriedades.put(CHAVE_TIPO_ENTRADA, "webservice");
                String url = textoURL.getText();
                String id = textoID.getText();
                String token = textoToken.getText();
                propriedades.put(CHAVE_WEBSERVICE_URL, url);
                propriedades.put(CHAVE_WEBSERVICE_ID, id);
                propriedades.put(CHAVE_WEBSERVICE_TOKEN, token);
                break;
        }
        String modeloEntrada = obtemValorSelecionado(comboBoxModeloEntrada);
        switch (modeloEntrada) {
            case MODELO_ENTRADA_SOAP_FINAL_RJ:
                propriedades.put(CHAVE_MODELO_ENTRADA, "soap_final_rj");
                break;
            case MODELO_ENTRADA_MODELO_ANTIGO:
                propriedades.put(CHAVE_MODELO_ENTRADA, "modelo_antigo");
                break;
        }
        String modalidadeJuridica = obtemValorSelecionado(comboBoxModalidadeJuridica);
        switch (modalidadeJuridica) {
            case MODALIDADE_JURIDICA_SIMPLES:
                propriedades.put(CHAVE_MODALIDADE_JURIDICA, "simples");
                break;
            case MODALIDADE_JURIDICA_LUCRO_REAL:
                propriedades.put(CHAVE_MODALIDADE_JURIDICA, "lucro_real");
                break;
            case MODALIDADE_JURIDICA_LUCRO_PRESUMIDO:
                propriedades.put(CHAVE_MODALIDADE_JURIDICA, "lucro_presumido");
                break;
        }

        String emailServidor = textoServidor.getText();
        propriedades.put(CHAVE_EMAIL_SERVIDOR, emailServidor);
        String emailPorta = textoPorta.getText();
        propriedades.put(CHAVE_EMAIL_PORTA, emailPorta);
        String emailUsuario = textoUsuario.getText();
        propriedades.put(CHAVE_EMAIL_USUARIO, emailUsuario);
        String emailSenha = textoSenha.getText();
        propriedades.put(CHAVE_EMAIL_SENHA, emailSenha);
        String emailDestinatario = textoDestinatario.getText();
        propriedades.put(CHAVE_EMAIL_DESTINATARIO, emailDestinatario);

        String sistema = obtemValorSelecionado(comboBoxSistema);
        String bancoURL = textoStringDeConexao.getText();
        String bancoUsuario = textoUsuarioBD.getText();
        String bancoSenha = textoSenhaBD.getText();
        switch (sistema) {
            case RETAGUARDA_ALTERDATA_POSTGRESQL:
                propriedades.put(CHAVE_HIBERNATE_DIALECT, RETAGUARDA_ALTERDATA_POSTGRESQL_DIALECT);
                propriedades.put(CHAVE_HIBERNATE_DRIVER, RETAGUARDA_ALTERDATA_POSTGRESQL_DRIVER);
                propriedades.put(CHAVE_HIBERNATE_URL, bancoURL);
                propriedades.put(CHAVE_HIBERNATE_USERNAME, bancoUsuario);
                propriedades.put(CHAVE_HIBERNATE_PASSWORD, bancoSenha);
                propriedades.put(CHAVE_RETAGUARDA, RETAGUARDA_ALTERDATA_POSTGRESQL_RETAGUARDA);

                 {
                    String cfops = textoCFOPs.getText();
                    propriedades.put(CHAVE_ALTERDATA_CFOPS, cfops);
                    String estadosEntrada = textoEstadosEntrada.getText();
                    propriedades.put(CHAVE_ALTERDATA_ESTADOS_ENTRADA, estadosEntrada);
                    String estadosSaida = textoEstadosSaida.getText();
                    propriedades.put(CHAVE_ALTERDATA_ESTADOS_SAIDA, estadosSaida);
                }
                break;
            case RETAGUARDA_ALTERDATA_SQLSERVER:
                propriedades.put(CHAVE_HIBERNATE_DIALECT, RETAGUARDA_ALTERDATA_SQLSERVER_DIALECT);
                propriedades.put(CHAVE_HIBERNATE_DRIVER, RETAGUARDA_ALTERDATA_SQLSERVER_DRIVER);
                propriedades.put(CHAVE_HIBERNATE_URL, bancoURL);
                propriedades.put(CHAVE_HIBERNATE_USERNAME, bancoUsuario);
                propriedades.put(CHAVE_HIBERNATE_PASSWORD, bancoSenha);
                propriedades.put(CHAVE_RETAGUARDA, RETAGUARDA_ALTERDATA_SQLSERVER_RETAGUARDA);

                 {
                    String cfops = textoCFOPs.getText();
                    propriedades.put(CHAVE_ALTERDATA_CFOPS, cfops);
                    String estadosEntrada = textoEstadosEntrada.getText();
                    propriedades.put(CHAVE_ALTERDATA_ESTADOS_ENTRADA, estadosEntrada);
                    String estadosSaida = textoEstadosSaida.getText();
                    propriedades.put(CHAVE_ALTERDATA_ESTADOS_SAIDA, estadosSaida);
                }
                break;
        }
        try {
            propriedades.store(new FileOutputStream(arquivoConfiguracoesLocal), null);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Um erro ocorreu ao tentar criar um arquivo de configurações. Entre em contato com o suporte do alerta fiscal.");
            System.exit(0);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoArquivoActionPerformed
        JFileChooser escolhaDeArquivo = new JFileChooser();
        escolhaDeArquivo.setCurrentDirectory(new File(System.getProperty("user.home")));
        int resultado = escolhaDeArquivo.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File arquivoSelecionado = escolhaDeArquivo.getSelectedFile();
            textoArquivo.setText(arquivoSelecionado.getAbsolutePath());
        }
    }//GEN-LAST:event_botaoArquivoActionPerformed

    private String obtemValorSelecionado(JComboBox jComboBox) {
        DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBox.getModel();
        return String.valueOf(model.getSelectedItem());
    }

    public static void rodar() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        ConfiguracaoGUI gui = new ConfiguracaoGUI();
        gui.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoArquivo;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JComboBox comboBoxAmbiente;
    private javax.swing.JComboBox comboBoxModalidadeJuridica;
    private javax.swing.JComboBox comboBoxModeloEntrada;
    private javax.swing.JComboBox comboBoxSistema;
    private javax.swing.JComboBox comboBoxTipoEntrada;
    private javax.swing.JLabel labelAmbiente;
    private javax.swing.JLabel labelArquivo;
    private javax.swing.JLabel labelCFOPs;
    private javax.swing.JLabel labelConfiguracoes;
    private javax.swing.JLabel labelDestinatario;
    private javax.swing.JLabel labelEstadosEntrada;
    private javax.swing.JLabel labelEstadosSaida;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelModalidadeJuridica;
    private javax.swing.JLabel labelModeloEntrada;
    private javax.swing.JLabel labelPorta;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JLabel labelSenhaBD;
    private javax.swing.JLabel labelServidor;
    private javax.swing.JLabel labelSistema;
    private javax.swing.JLabel labelStringDeConexao;
    private javax.swing.JLabel labelTipoEntrada;
    private javax.swing.JLabel labelToken;
    private javax.swing.JLabel labelURL;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelUsuarioBD;
    private javax.swing.JPanel painelAlterdata;
    private javax.swing.JPanel painelBancoDeDados;
    private javax.swing.JPanel painelEmail;
    private javax.swing.JTabbedPane painelPrincipal;
    private javax.swing.JPanel painelRevisao;
    private javax.swing.JPanel painelRevisaoWebService;
    private javax.swing.JPanel painelRevisaoXML;
    private javax.swing.JTextField textoArquivo;
    private javax.swing.JTextField textoCFOPs;
    private javax.swing.JTextField textoDestinatario;
    private javax.swing.JTextField textoEstadosEntrada;
    private javax.swing.JTextField textoEstadosSaida;
    private javax.swing.JTextField textoID;
    private javax.swing.JTextField textoPorta;
    private javax.swing.JTextField textoSenha;
    private javax.swing.JTextField textoSenhaBD;
    private javax.swing.JTextField textoServidor;
    private javax.swing.JTextField textoStringDeConexao;
    private javax.swing.JTextField textoToken;
    private javax.swing.JTextField textoURL;
    private javax.swing.JTextField textoUsuario;
    private javax.swing.JTextField textoUsuarioBD;
    // End of variables declaration//GEN-END:variables
}
